version: "3"
services:
  minter-postgres:
    restart: always
    image: postgres:11
    volumes:
      - minter-db:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"

volumes:
  minter-db:
